### ISSUE TITLE
Refactor main

### ISSUE THREAD

**Issue by charleygros** [neuropoly/ivado-medical-imaging#230]
The last step of the refactoring that we planned is the refactoring of `main.py`, which goes along with the config files, e.g. #193 & #167.

### Main
Suggestion:
1. `main.py`:
- keep the `run_main` ([here](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L885))
- config file / param parsing
- eventually deal with [data_loader](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L151) since there is a lot of duplication between the training, validation and testing loader

2. `train.py`, `test.py`: basically what is currently in `cmd_train` and `cmd_test` but modularised in order to improve clarity.
For instance:
- `get_loss_function` instead of [these lines](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L265)
- `get_lr_scheduler` instead of [these lines](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L235)
- `get_model` instead of t[hese lines](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/main.py#L198)
`train.py` will be in charge to generate a `log.json`, including ivadomed version and dataset info see [here](https://github.com/neuropoly/ivado-medical-imaging/issues/182).
Another objective would be to use the loop from `cmd_test` in `segment_volume` since these lines are mostly duplicated

3. `eval.py`: basically what is currently in `cmd_eval`. Also maybe also pull [Evaluation3DMetrics](https://github.com/neuropoly/ivado-medical-imaging/blob/06c1d6ce7132946541d0951f128d1a8ffe0a9c80/ivadomed/utils.py#L29) in this file.

### Config files

To achieve [this](https://github.com/neuropoly/ivado-medical-imaging/issues/193#issuecomment-631145765), I can see 2 main avenues:
1. we keep our (long) config files and `main.py` will be in charge to split the info between inference, and training and save it into the log_directory
2. we split our config files (config_ms_lesion/training.json, inference.json, evaluation.json) and the main will simply copy/paste these files in the log_directory.
If we go with (2), we will need to run `ivadomed model_ms_lesion/training.json` to trigger the training etc. (which is maybe more handy than opening the json file, changing `cmd_train` by `cmd_test`)

Any thoughts? We could start to draft a PR in parallel

**Comment by andreanne-lemay** [comment]
That seems like a great plan! For the config files, I am really not sure about having more than one file for a single model it seems like a lot of files to deal with. A big part of our config file is the transforms. Instead of having transformation_training, transformation_validation, transformation_testing, we could simply have transformation. In the transforms, we could add a parameter (just like "applied_to") to indicate when the transformation should be used (e.i. RandomAffine: {rotation: 10, dataset_type: ["training"]}. No parameter would mean apply during training, validation and testing. This will remove a few lines already. Also, some parameters have dependencies. For instance, mixup_alpha is not used if mixup_bool is false. Why not keep only mixup_alpha=XX if we want mixup and mixup_alpha=null if not. We could also reorganize some dependent parameters to make the file clearer: length_3D, paddind_3D, attention_unet, n_filters only applies if unet_3D is true. Regrouping them makes it clearer that I don't have to modify them, if I am not using unet3D. Same goes for some parameters related to HeMIS or FiLM.

I am not closed to the idea of having more than one config file (we would gain in clarity), I just think it's less convenient. Here is a config file suggestion to illustrate the ideas I mentioned:

```json
{
    "command": "test",
    "gpu": 0,
    "target_suffix": ["_seg-tumor"],
    "roi": {
        "suffix": null,
        "slice_filter_roi": null
    },
    "bids_path": "/home/andreanne/Documents/dataset/toy_dataset",
    "random_seed": 6,
    "contrast_train_validation": ["T1w", "T2w"],
    "contrast_test": ["T1w","T2w"],
    "contrast_balance": {},
    "center_test": [],
    "batch_size": 1,
    "dropout_rate": 0.3,
    "batch_norm_momentum": 0.9,
    "loss": {"name": "dice"},
    "log_directory": "HeMIS",
    "FiLM": {
        "metadata": "without",
        "film_layers": []
    },
    "HeMIS": {
        "applied": false,
        "missing_probability": 0.00001,
        "missing_probability_growth": 0.9,
        "ram": true,
        "hdf5_path": "/home/andreanne/Documents/dataset/HeMIS.hdf5",
        "csv_path": "/home/andreanne/Documents/dataset/HeMIS.csv",
        "target_lst": ["T2w"],
        "roi_lst": null
    },
    "unet3D": {
        "applied": true,
        "length_3D": [256, 128, 16],
        "padding_3D": 0,
        "attention_unet": false,
        "n_filters": 1
    },
    "transfer_learning": {
        "retrain_model": null,
        "retrain_fraction": 1.0
    },
    "training_time": {
        "num_epochs": 100,
        "early_stopping_patience": 50,
        "early_stopping_epsilon": 0.001
    },
    "scheduler": {
        "initial_lr": 0.001,
        "lr_scheduler": {"name": "CosineAnnealingLR", "base_lr": 1e-5, "max_lr": 1e-2},
    },
    "depth": 4,
    "mixup_alpha": null,
    "multichannel": false,
    "out_channel": 1,
    "balance_samples": false,
    "slice_axis": "sagittal",
    "split_method": "per_patient",
    "train_test_fraction": [0.6, 0.2],
    "binarize_prediction": true,
    "uncertainty": {"epistemic": false, "aleatoric": false, "n_it": 10},
    "slice_filter": {
        "filter_empty_mask": true,
        "filter_empty_input": true
    },
    "eval_params": {
        "targetSize": {"unit": "vox", "thr": [20, 100]},
        "removeSmall": {"unit": "vox", "thr": 3},
        "overlap": {"unit": "vox", "thr": 3}
    },
    "transformation": {
        "Resample":
        {
            "wspace": 1,
            "hspace": 1,
            "dspace": 2
        },
        "CenterCrop": {
            "size": [256, 128, 16]
        },
        "RandomAffine": {
            "degrees": 4.6,
            "translate": [0.03, 0.03],
            "scale": [0.98, 1.02],
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
      "NumpyToTensor": {},
      "NormalizeInstance": {"applied_to": ["im"]}
    },
    "debugging": false
}

}
```

**Comment by charleygros** [comment]
I agree! And your suggestion of config file fits with what I had in mind for the `main.py` --> great! Let's  do that
